### ISSUE TITLE
Imagem de perfil no README

### ISSUE THREAD

**Issue by rayzersrc** [kaduej/NLWeSports#1]
Opa, olha ai a imagem como você queria, fiz no Photopea, mas está em baixa qualidade por causa da original, qualquer coisa edita por lá e substitui no seu. Para editar, você abre a imagem no Photopea, vai na ferramenta de Selecionar em Elipse, no topo escolhe Tamanho Fixo e coloca a resolução da imagem que você abriu, arrasta em cima da imagem, ajusta a seleção, botão direito e depois em Inverso, deleta e está pronto, só exportar em .png. o/

## :man_artist: Autor

<img src="https://user-images.githubusercontent.com/111004726/190391399-98a6a45e-da62-487f-971f-cebca79b1795.png" width="60px">

[kaduej](https://github.com/kaduej) :wave:

```md
## :man_artist: Autor

<img src="https://user-images.githubusercontent.com/111004726/190391399-98a6a45e-da62-487f-971f-cebca79b1795.png" width="60px">

[kaduej](https://github.com/kaduej) :wave:
```

**Comment by kaduej** [comment]
nossa mano, vlw demais, eu tentei fazer agora no Photopea (não conhecia essa ferramenta online, achei top) e ficou grande mesmo assim, vou usar a que vc fez pra mim por enquanto, muito obrigado novamente! tamo junto

**Comment by rayzersrc** [comment]
Suaveeeee o/
Grande o tamanho em MB? Você pode diminuir a resolução no Photopea, no menu Imagem > Tamanho da Imagem. Ai você só substitui o arquivo avatargit.png e está tudo certo. Se quiser aumentar o tamanho da sua imagem no README, só mudar o width ali no final:
```html
<img src="./assets/avatargit.png" width="60px">
```
